# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "centos7", autostart: false do |centos7|
    centos7.vm.box = "centos/7"
  end

  config.vm.define "almalinux8", autostart: false do |almalinux8|
    almalinux8.vm.box = "almalinux/8"
  end

  config.vm.define "almalinux9", autostart: false do |almalinux9|
    almalinux9.vm.box = "almalinux/9"
  end

  config.vm.define "rockylinux8", autostart: false do |rockylinux8|
    rockylinux8.vm.box = "rockylinux/8"
  end

  config.vm.define "rockylinux9", autostart: false do |rockylinux9|
    rockylinux9.vm.box = "rockylinux/9"
  end

  config.vm.define "ubuntu_lunar", autostart: false do |ubuntu_lunar|
    ubuntu_lunar.vm.box = "ubuntu/lunar64"
  end

  config.vm.define "ubuntu_jammy", autostart: false do |ubuntu_jammy|
    ubuntu_jammy.vm.box = "ubuntu/jammy64"
  end

  config.vm.define "ubuntu_focal", autostart: false do |ubuntu_focal|
    ubuntu_focal.vm.box = "ubuntu/focal64"
  end

  config.vm.define "ubuntu_bionic", autostart: false do |ubuntu_bionic|
    ubuntu_bionic.vm.box = "ubuntu/bionic64"
  end

  config.vm.define "ubuntu_xenial", autostart: false do |ubuntu_xenial|
    ubuntu_xenial.vm.box = "ubuntu/xenial64"
  end

  config.vm.define "debian_buster", autostart: false do |debian_buster|
    debian_buster.vm.box = "debian/buster64"
  end

  config.vm.define "debian_bullseye", autostart: false do |debian_bullseye|
    debian_bullseye.vm.box = "debian/bullseye64"
  end

  config.vm.define "debian_bookworm", autostart: false do |debian_bookworm|
    debian_bookworm.vm.box = "debian/bookworm64"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "test.yml"
    ansible.limit = "all"
  end

  config.vm.provider "virtualbox"
end
